version: '3'
services:
  app:
    image: spring-boot-app:latest
    environment:
      DB_URL: jdbc:postgresql://db:5432/my_database
      DB_USERNAME: my_user
      DB_PASSWORD: my_password
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"

